// ---------------------------------------------------------------------------
// Unit test for the schema auto-discovery feature in server/utils/dashboard/tables.ts
//
// This test verifies the end-to-end "zero-config" promise:
//   1. define a pgTable() in a Drizzle schema (we use `private_messages` from
//      server/database/schema.ts as the guinea pig)
//   2. register that schema object into SCHEMA_REGISTRY via
//      registerDrizzleSchema()
//   3. ask getRegisteredTable('private_messages') — it MUST NOT return
//      undefined, even though private_messages is NOT in the manual TABLES[]
//      array and registerDashboardTable() was NEVER called for it
//   4. the inferred FieldMeta list must have the correct shape: the right
//      keys, correct column-type → FieldType mapping, correct
//      editable/showInForm flags for auto-generated columns, sensible
//      TableFeatures (soft-delete because deletedAt exists, etc.)
//
// All of this runs WITHOUT touching `db` or `h3`, so it can live under
// `test/unit/server/` and be executed by `pnpm test` (vitest) in complete
// isolation.
// ---------------------------------------------------------------------------
import { describe, it, expect } from 'vitest'
import * as mainSchema from '../../../server/database/schema'
import {
  autoDiscoverTable,
  getRegisteredTable,
  registerDrizzleSchema,
  listAllAutoDiscoverableTables,
  // Intentionally NOT imported — the test's whole point is proving we don't
  // need manual TABLES entries for newly defined tables:
  // registerDashboardTable
} from '../../../server/utils/dashboard/tables'
import type { FieldType, TableMeta } from '~/types/dashboard'

type ColSpec = {
  key: string
  type: FieldType
  nullable: boolean
  editable: boolean
  showInForm: boolean
  showInTable: boolean
}

describe('schema auto-discovery (dashboard/tables.ts)', () => {
  it('registerDrizzleSchema accepts the main project schema export without throwing', () => {
    expect(() => registerDrizzleSchema(mainSchema)).not.toThrow()
  })

  it('autoDiscoverTable("private_messages") returns a non-null RegisteredTable', () => {
    registerDrizzleSchema(mainSchema)
    const reg = autoDiscoverTable('private_messages')
    expect(reg).not.toBeNull()
    expect(reg?.meta.table).toBe('private_messages')
  })

  it('autoDiscoverTable("nonexistent_xyz_table") returns null', () => {
    registerDrizzleSchema(mainSchema)
    expect(autoDiscoverTable('nonexistent_xyz_table')).toBeNull()
  })

  describe('inferred FieldMeta for private_messages table', () => {
    function pmMeta(): TableMeta {
      const reg = autoDiscoverTable('private_messages')!
      return reg.meta
    }

    it('contains every declared column', () => {
      const keys = pmMeta().fields.map(f => f.key).sort()
      // id, senderId, receiverId, content, readAt, createdAt
      expect(keys).toEqual([
        'content',
        'createdAt',
        'id',
        'readAt',
        'receiverId',
        'senderId',
      ])
    })

    const specs: ColSpec[] = [
      // id: serial PK → autogenerated, not editable
      { key: 'id', type: 'number', nullable: false, editable: false, showInForm: false, showInTable: true },
      // senderId/receiverId: *_id → relation (target: users)
      { key: 'senderId', type: 'relation', nullable: false, editable: true, showInForm: true, showInTable: true },
      { key: 'receiverId', type: 'relation', nullable: false, editable: true, showInForm: true, showInTable: true },
      // content: text not null → textarea, list-hidden
      { key: 'content', type: 'textarea', nullable: false, editable: true, showInForm: true, showInTable: false },
      // readAt: timestamp nullable → datetime
      { key: 'readAt', type: 'datetime', nullable: true, editable: true, showInForm: true, showInTable: true },
      // createdAt: audit timestamp → non-editable
      { key: 'createdAt', type: 'datetime', nullable: false, editable: false, showInForm: false, showInTable: true },
    ]
    for (const s of specs) {
      it(`${s.key}: type=${s.type} nullable=${s.nullable} editable=${s.editable} showInForm=${s.showInForm} showInTable=${s.showInTable}`, () => {
        const f = pmMeta().fields.find(f => f.key === s.key)
        expect(f).toBeDefined()
        expect(f!.type).toBe(s.type)
        expect(f!.nullable).toBe(s.nullable)
        expect(f!.editable).toBe(s.editable)
        expect(f!.showInForm).toBe(s.showInForm)
        expect(f!.showInTable).toBe(s.showInTable)
      })
    }

    it('senderId/receiverId infer a relation target by pluralizing the column base', () => {
      const f = pmMeta().fields.find(x => x.key === 'senderId')!
      expect(f.relation).toBeDefined()
      // senderId → "sender" → "senders" (not a real table, but that's the
      // naming-convention behavior)
      expect((f as any).relation?.table).toBe('senders')
      expect((f as any).relation?.labelKey).toBe('name')
      expect((f as any).relation?.valueKey).toBe('id')
    })

    it('non-nullable/non-autogenerated fields get validation = { required: true }', () => {
      const content = pmMeta().fields.find(f => f.key === 'content')!
      expect(content.validation?.required).toBe(true)
      // readAt is nullable — should NOT be forced required
      const readAt = pmMeta().fields.find(f => f.key === 'readAt')!
      expect(readAt.validation?.required).not.toBe(true)
    })
  })

  describe('inferred TableFeatures for private_messages', () => {
    function features() {
      return autoDiscoverTable('private_messages')!.meta.features
    }

    it('softDelete=false because there is no deletedAt column', () => {
      expect(features().softDelete).toBe(false)
    })

    it('search picks text/textarea columns as default full-text filterables', () => {
      expect(features().search).toEqual(expect.arrayContaining(['content']))
    })

    it('defaultSort falls back to the first sortable column (updatedAt → id)', () => {
      expect(features().defaultSort).toEqual({ field: 'id', order: 'desc' })
    })
  })

  it('getRegisteredTable("private_messages") falls back to auto-discover when TABLES[] has no explicit entry', () => {
    // Important: `roles` / `users` etc. ARE manually registered, so they
    // never hit the auto-discover path.  `private_messages` is intentionally
    // NOT in the TABLES[] array — so this call forces SCHEMA_REGISTRY lookup.
    registerDrizzleSchema(mainSchema)
    const reg = getRegisteredTable('private_messages')
    expect(reg).toBeDefined()
    expect(reg!.meta.fields).toBeInstanceOf(Array)
    expect(reg!.meta.fields.length).toBeGreaterThan(0)
  })

  it('listAllAutoDiscoverableTables() enumerates tables that have no manual entry', () => {
    registerDrizzleSchema(mainSchema)
    // private_messages / tokens / notificationReads / oauthAccounts etc. are
    // all defined in the main schema but NOT manually registered into
    // TABLES[] — so they all appear in the auto-discovered list.
    const autos = listAllAutoDiscoverableTables()
    const tables = new Set(autos.map(r => r.meta.table))
    // `private_messages` is our zero-config guinea pig; must definitely be there.
    expect(tables.has('private_messages')).toBe(true)
    // Manually-registered tables like `roles`/`users`/`configs`/`files`
    // MUST NOT be re-emitted.
    for (const t of ['roles', 'users', 'configs', 'files']) {
      expect(tables.has(t)).toBe(false)
    }
  })
})