<template>
  <!-- eslint-disable vue/no-v-html -->
  <!-- Content is generated by renderMarkdown: html:true + sanitizeHtml cleans dangerous tags/events/protocols + link/image whitelist -->
  <div
    class="md-body"
    :class="inline ? 'md-inline' : 'md-block'"
    v-html="html"
  />
  <!-- eslint-enable vue/no-v-html -->
</template>

<script setup lang="ts">
// katex and highlight.js theme styles load with the component
import 'katex/dist/katex.min.css'
import 'highlight.js/styles/github-dark.css'

const props = withDefaults(
  defineProps<{
    source: string
    /** Inline mode: renders only inline syntax (bold/inline code/links/inline math), used for short texts like options */
    inline?: boolean
  }>(),
  { inline: false }
)

// Rendering logic lives in utils/markdown.ts (auto-imported); SSR and client results are identical
const html = computed(() => renderMarkdown(props.source, props.inline))
</script>

<!-- Not scoped: v-html generated nodes can't get the scope id, so control scope uniformly with the .md-body prefix -->
<style>
.md-body {
  color: inherit;
  font-size: inherit;
  line-height: inherit;
  overflow-wrap: anywhere;
}

/* Inline mode participates in layout as an inline element (e.g. option letter followed by math/bold) */
.md-body.md-inline {
  display: inline;
}

/* Remove extra margins on first/last elements to avoid stretching compact layouts */
.md-body > :first-child { margin-top: 0; }
.md-body > :last-child { margin-bottom: 0; }

/* Headings: scale proportionally, inherit current text color (readable on ink/light themes) */
.md-body h1,
.md-body h2,
.md-body h3,
.md-body h4,
.md-body h5,
.md-body h6 {
  font-weight: 600;
  line-height: 1.4;
  margin: 0.8em 0 0.4em;
  color: inherit;
}
.md-body h1 { font-size: 1.25em; }
.md-body h2 { font-size: 1.18em; }
.md-body h3 { font-size: 1.1em; }
.md-body h4 { font-size: 1.05em; }
.md-body h5,
.md-body h6 { font-size: 1em; }

/* Paragraphs and text */
.md-body p { margin: 0.5em 0; }
.md-body strong { font-weight: 600; }
.md-body em { font-style: italic; }
.md-body del,
.md-body s { opacity: 0.7; }
.md-body a {
  color: inherit;
  text-decoration: underline;
  text-underline-offset: 2px;
}

/* Lists: restore styles reset by tailwind preflight */
.md-body ul,
.md-body ol {
  padding-left: 1.5em;
  margin: 0.4em 0;
}
.md-body ul { list-style: disc; }
.md-body ol { list-style: decimal; }
.md-body li { margin: 0.15em 0; }
.md-body li::marker { color: inherit; opacity: 0.6; }
.md-body li > ul,
.md-body li > ol { margin: 0.15em 0; }

/* Task list: remove bullets, checkbox on the same line as text */
.md-body .md-task-item { list-style: none; padding-left: 0.2em; }
.md-body .md-task-item .md-task-para { display: inline; margin: 0; }
.md-body .md-checkbox {
  margin-right: 0.4em;
  vertical-align: -0.15em;
  accent-color: currentColor;
}

/* Blockquote: current-color left border + slight opacity reduction, unobtrusive on light/dark backgrounds */
.md-body blockquote {
  margin: 0.5em 0;
  padding: 0.1em 0 0.1em 0.8em;
  border-left: 3px solid currentColor;
  opacity: 0.85;
}

/* Inline code: neutral gray translucent background, readable on light/dark backgrounds */
.md-body code {
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace;
  font-size: 0.875em;
}
.md-body :not(pre) > code {
  background: rgba(127, 127, 127, 0.18);
  padding: 0.1em 0.35em;
  border-radius: 4px;
}

/* Code block: github-dark background + rounded corners + horizontal scroll, language label in top-right */
.md-body .md-code-block {
  position: relative;
  margin: 0.6em 0;
  border-radius: 8px;
  overflow: hidden;
}
.md-body .md-code-block pre {
  margin: 0;
  padding: 0.8em;
  overflow-x: auto;
  background: #0d1117; /* keep consistent with the github-dark theme base color for continuous background on horizontal scroll */
}
.md-body .md-code-block pre code {
  display: block;
  padding: 0;
  background: transparent;
  font-size: 0.85em;
  line-height: 1.6;
}
.md-body .md-code-lang {
  position: absolute;
  top: 0;
  right: 0;
  z-index: 1;
  padding: 0.1em 0.6em;
  font-size: 0.68em;
  letter-spacing: 0.05em;
  color: rgba(230, 237, 243, 0.55);
  background: rgba(255, 255, 255, 0.07);
  border-radius: 0 8px 0 8px;
  pointer-events: none;
  user-select: none;
}

/* Table: neutral gray border + light header background, supports horizontal scroll */
.md-body table {
  display: block;
  width: max-content;
  max-width: 100%;
  overflow-x: auto;
  border-collapse: collapse;
  margin: 0.6em 0;
  font-size: 0.9em;
}
.md-body th,
.md-body td {
  border: 1px solid rgba(128, 128, 128, 0.35);
  padding: 0.3em 0.6em;
  text-align: left;
  white-space: nowrap;
}
.md-body th {
  background: rgba(127, 127, 127, 0.15);
  font-weight: 600;
}

/* Images: responsive + rounded corners */
.md-body img {
  max-width: 100%;
  height: auto;
  border-radius: 6px;
  margin: 0.4em 0;
}

/* Horizontal rule */
.md-body hr {
  border: none;
  border-top: 1px solid rgba(128, 128, 128, 0.35);
  margin: 1em 0;
}

/* Math: inline formulas follow the text baseline, block formulas are centered and horizontally scrollable */
.md-body .katex { font-size: 1.05em; }
.md-body .math-block,
.md-body .katex-display {
  margin: 0.6em 0;
  overflow-x: auto;
  overflow-y: hidden;
  text-align: center;
}
.md-body .katex-display > .katex { white-space: nowrap; }
</style>
